name: hackathon_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  # Core Flutter SDK
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.0.3

  # Routing
  go_router: ^17.0.0

  # Annotation
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Camera and Image
  image_picker: ^1.2.0
  image: ^4.5.4

  # Animation
  lottie: ^3.3.2

  # Image caching
  cached_network_image: ^3.4.1

  # Utility
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  pedantic_mono: ^1.33.0
  freezed: ^3.2.3
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  

flutter:
  uses-material-design: true
